### ISSUE TITLE
open activy tab occured 500 error

### ISSUE THREAD

**Issue by archonwang** [deecay/redmine_pivot_table#33]
error log 

```
Started GET "/projects/tmx/pivottables?table=activity" for 192.168.60.238 at 2016-12-15 11:51:16 +0800
Processing by PivottablesController#index as HTML
  Parameters: {"table"=>"activity", "project_id"=>"tmx"}
  Current user: hui.wang (id=8)
Completed 500 Internal Server Error in 215ms (ActiveRecord: 40.6ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_request.text.erb (0.3ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_session.text.erb (1.6ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.1ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_environment.text.erb (2.5ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.1ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_backtrace.text.erb (0.1ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.1ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb (14.5ms)

NoMethodError (undefined method `where' for #<Hash:0x0000000673f928>):
  lib/plugins/acts_as_activity_provider/lib/acts_as_activity_provider.rb:59:in `find_events'
  lib/redmine/activity/fetcher.rb:91:in `block (2 levels) in events'
  lib/redmine/activity/fetcher.rb:90:in `each'
  lib/redmine/activity/fetcher.rb:90:in `block in events'
  lib/redmine/activity/fetcher.rb:89:in `each'
  lib/redmine/activity/fetcher.rb:89:in `events'
  plugins/redmine_pivot_table/app/controllers/pivottables_controller.rb:52:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'


Started GET "/projects/tmx/pivottables?table=activity" for 192.168.60.238 at 2016-12-15 11:51:17 +0800
Processing by PivottablesController#index as */*
  Parameters: {"table"=>"activity", "project_id"=>"tmx"}
  Current user: hui.wang (id=8)
Completed 500 Internal Server Error in 187ms (ActiveRecord: 40.8ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_request.text.erb (0.5ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.1ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_session.text.erb (1.5ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.1ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_environment.text.erb (2.7ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.1ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_backtrace.text.erb (0.1ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.1ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb (14.3ms)

NoMethodError (undefined method `where' for #<Hash:0x0000000673f928>):
  lib/plugins/acts_as_activity_provider/lib/acts_as_activity_provider.rb:59:in `find_events'
  lib/redmine/activity/fetcher.rb:91:in `block (2 levels) in events'
  lib/redmine/activity/fetcher.rb:90:in `each'
  lib/redmine/activity/fetcher.rb:90:in `block in events'
  lib/redmine/activity/fetcher.rb:89:in `each'
  lib/redmine/activity/fetcher.rb:89:in `events'
  plugins/redmine_pivot_table/app/controllers/pivottables_controller.rb:52:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

```

**Comment by deecay** [comment]
Hi,

Do you have knowledgebase or meetings plugin installed?
Does the error go away after removing other plugins?

**Comment by archonwang** [comment]
@deecay , I will check it . I have installed redmine_knowledge and redmine_meeting all.
