### ISSUE TITLE
please add support for redmine 3.3.2

### ISSUE THREAD

**Issue by deathrush** [deecay/redmine_pivot_table#37]
browser displayed error:
```
Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.
```

redmine production.log:
```
Started GET "/redmine/projects/test_project_1/pivottables" for 114.80.235.189 at 2017-03-25 15:14:59 +0800
Processing by PivottablesController#index as HTML
  Parameters: {"project_id"=>"test_project_1"}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 39ms (ActiveRecord: 8.9ms)

ArgumentError (invalid value for Integer(): ""):
  app/models/issue_query.rb:359:in `issues'
  plugins/redmine_pivot_table/app/controllers/pivottables_controller.rb:64:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by rliebe** [comment]
I have the same error.

**Comment by deecay** [comment]
I will look into it.

**Comment by rodabt** [comment]
Same here

**Comment by rodabt** [comment]
I think it's about the issue limit. After setting a value in the plugin configuration tab (not leaving it empty) it worked...
