### ISSUE TITLE
Getting 500 Error 

### ISSUE THREAD

**Issue by destiny931** [deecay/redmine_pivot_table#46]
I installed and activated the pivot table plugin in my project.  When trying to access the Pivot table, I get redmine 500 error.  Below is what is displayed in the log.  Any suggestions?

 Rendered plugins/redmine_pivot_table/app/views/pivottables/index.html.erb within layouts/base (396.0ms)
Completed 500 Internal Server Error in 703ms (ActiveRecord: 128.0ms)

ActionView::Template::Error (invalid date):
    57:            <% if @table == "activity" %>
    58:              data = <%= raw parse_events(@events).to_json %>;
    59:            <% else %>
    60:              data = <%= raw parse_issues(@issues).to_json %>;
    61:            <% end %>
    62: 
    63:            var dateFormat = $.pivotUtilities.derivers.dateFormat;
  plugins/redmine_pivot_table/app/helpers/pivottables_helper.rb:68:in `parse'
  plugins/redmine_pivot_table/app/helpers/pivottables_helper.rb:68:in `block (2 levels) in parse_issues'
  plugins/redmine_pivot_table/app/helpers/pivottables_helper.rb:57:in `each'
  plugins/redmine_pivot_table/app/helpers/pivottables_helper.rb:57:in `block in parse_issues'
  plugins/redmine_pivot_table/app/helpers/pivottables_helper.rb:55:in `each'
  plugins/redmine_pivot_table/app/helpers/pivottables_helper.rb:55:in `parse_issues'
  plugins/redmine_pivot_table/app/views/pivottables/index.html.erb:60:in `_9045018317ee2a7f6851f459d5112785'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by deecay** [comment]
Please see if this is resolved with current master. Thanks!

**Comment by konpega** [comment]
Hi deecay
I have the same error, and this plugin prevents to enter the My account for example, sometimes cause the error when you try to see another project or issues. This is not stable. I am using Redmine 4.0.2-3 on Windows.
Just to be able to work with this plugin I downgrade from 4.1.0-8 and transferred my data. Also I opened an issue here for the version 4.1.
