### ISSUE TITLE
Internal error : undefined method `lu'

### ISSUE THREAD

**Issue by Jeffsonery** [deecay/redmine_pivot_table#48]
redmine 2.6
ruby 2.0.0p598
rails 3.2

ActionView::Template::Error (undefined method `lu' for #<#<Class:0x007f620dd5adb0>:0x007f620dd59320>):
    57:            <% if @table == "activity" %>
    58:              data = <%= raw parse_events(@events).to_json %>;
    59:            <% else %>
    60:              data = <%= raw parse_issues(@issues).to_json %>;
    61:            <% end %>
    62: 
    63:            var dateFormat = $.pivotUtilities.derivers.dateFormat;
  plugins/redmine_pivot_table/app/helpers/pivottables_helper.rb:57:in `parse_issues'
  plugins/redmine_pivot_table/app/views/pivottables/index.html.erb:60:in `_plugins_redmine_pivot_table_app_views_pivottables_index_html_erb__462367280822265617_70029557823260'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_view/template.rb:145:in `block in render'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.19/lib/active_support/notifications.rb:125:in `instrument'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_view/template.rb:143:in `render'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_view/renderer/template_renderer.rb:47:in `block (2 levels) in render_template'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.19/lib/active_support/notifications.rb:123:in `block in instrument'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.19/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.19/lib/active_support/notifications.rb:123:in `instrument'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_view/renderer/template_renderer.rb:46:in `block in render_template'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_view/renderer/template_renderer.rb:54:in `render_with_layout'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_view/renderer/template_renderer.rb:45:in `render_template'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_view/renderer/template_renderer.rb:18:in `render'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_view/renderer/renderer.rb:36:in `render_template'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_view/renderer/renderer.rb:17:in `render'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/abstract_controller/rendering.rb:110:in `_render_template'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_controller/metal/streaming.rb:225:in `_render_template'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/abstract_controller/rendering.rb:103:in `render_to_body'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_controller/metal/renderers.rb:28:in `render_to_body'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/abstract_controller/rendering.rb:88:in `render'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_controller/metal/rendering.rb:16:in `render'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.19/lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
  /opt/redmine-2.6.0-3/ruby/lib/ruby/2.0.0/benchmark.rb:296:in `realtime'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.19/lib/active_support/core_ext/benchmark.rb:5:in `ms'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_controller/metal/instrumentation.rb:40:in `block in render'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
  vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.19/lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_controller/metal/instrumentation.rb:39:in `render'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_controller/metal/implicit_render.rb:5:in `send_action'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/abstract_controller/base.rb:167:in `process_action'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_controller/metal/rendering.rb:10:in `process_action'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:502:in `_run__854851261184540246__process_action__1368570509716746595__callbacks'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:405:in `__run_callback'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/abstract_controller/callbacks.rb:17:in `process_action'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_controller/metal/rescue.rb:29:in `process_action'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.19/lib/active_support/notifications.rb:123:in `block in instrument'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.19/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.19/lib/active_support/notifications.rb:123:in `instrument'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.19/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/abstract_controller/base.rb:121:in `process'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/abstract_controller/rendering.rb:45:in `process'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_controller/metal.rb:203:in `dispatch'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_controller/metal.rb:246:in `block in action'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_dispatch/routing/route_set.rb:73:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_dispatch/routing/route_set.rb:36:in `call'
  vendor/bundle/ruby/2.0.0/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
  vendor/bundle/ruby/2.0.0/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
  vendor/bundle/ruby/2.0.0/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_dispatch/routing/route_set.rb:608:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-openid-1.4.1/lib/rack/openid.rb:99:in `call'
  vendor/bundle/ruby/2.0.0/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/etag.rb:23:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/conditionalget.rb:25:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_dispatch/middleware/head.rb:14:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_dispatch/middleware/flash.rb:242:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
  vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_dispatch/middleware/cookies.rb:341:in `call'
  vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.19/lib/active_record/query_cache.rb:64:in `call'
  vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:405:in `_run__1139437522953174664__call__1519298350791354626__callbacks'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:405:in `__run_callback'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  vendor/bundle/ruby/2.0.0/gems/railties-3.2.19/lib/rails/rack/logger.rb:32:in `call_app'
  vendor/bundle/ruby/2.0.0/gems/railties-3.2.19/lib/rails/rack/logger.rb:16:in `block in call'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.19/lib/active_support/tagged_logging.rb:22:in `tagged'
  vendor/bundle/ruby/2.0.0/gems/railties-3.2.19/lib/rails/rack/logger.rb:16:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_dispatch/middleware/request_id.rb:22:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
  vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.19/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/action_dispatch/middleware/static.rb:63:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
  vendor/bundle/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:245:in `fetch'
  vendor/bundle/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:185:in `lookup'
  vendor/bundle/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:66:in `call!'
  vendor/bundle/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
  vendor/bundle/ruby/2.0.0/gems/railties-3.2.19/lib/rails/engine.rb:484:in `call'
  vendor/bundle/ruby/2.0.0/gems/railties-3.2.19/lib/rails/application.rb:231:in `call'
  vendor/bundle/ruby/2.0.0/gems/railties-3.2.19/lib/rails/railtie/configurable.rb:30:in `method_missing'
  vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/builder.rb:134:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/urlmap.rb:64:in `block in call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/urlmap.rb:49:in `each'
  vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/urlmap.rb:49:in `call'
  passenger (4.0.53) lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
  passenger (4.0.53) lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  passenger (4.0.53) lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  passenger (4.0.53) lib/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'

what do i do ?
or did i miss sth when installing this plugin?

**Comment by mdallastella** [comment]
Same issue here, with:

Debian 9
Redmine 3.1.7
ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
rails 4.2.7.1

```
Started GET "/projects/sys/pivottables" for 172.16.20.10 at 2018-09-05 15:05:38 +0200
Processing by PivottablesController#index as HTML
  Parameters: {"project_id"=>"sys"}
  Current user: admin (id=1)
  Rendered plugins/redmine_pivot_table/app/views/pivottables/index.html.erb within layouts/base (48.9ms)
Completed 500 Internal Server Error in 165ms (ActiveRecord: 93.1ms)

ActionView::Template::Error (undefined method `lu' for #<#<Class:0x00563326595150>:0x007f3a44494730>
Did you mean?  l):
    55:            <% if @table == "activity" %>
    56:              data = <%= raw parse_events(@events).to_json %>;
    57:            <% else %>
    58:              data = <%= raw parse_issues(@issues).to_json %>;
    59:            <% end %>
    60: 
    61:            var dateFormat = $.pivotUtilities.derivers.dateFormat;
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by quinoshita** [comment]
Same issue too. Therefore, I just use drilldown branch code. It works fine.

By the way, "lu"method called by pivottables_helper.rb:57 is in /assets/javascripts/d3.min.js. But number of argument seems different.
